# Generated by Django 4.2 on 2023-04-30 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPGapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
